### PR TITLE
Add optional params to Params type definition.

### PR DESCRIPTION
**Pull request by keeema**
Breaking change.

### CODE REVIEW

**Comment by Bobris** [comment]
Usecase? And why it is braking change?

**Comment by keeema** [comment]
Use case:
`export interface IData extends b.IRouteHandlerData {
    routeParams: { someId?: string };
}`

...routeParams, in fact, are always string | undefined, because you are not able to guarantee the value. But if you expect correct using of transitions, it should at least correspond with possible optional route params definition.

It is breaking change, because some code can count on `string` in routeParams or e.g. b.getActiveParams()[routeParameter]

**Comment by Bobris** [comment]
I actually thought that type of `b.getActiveParams()["x"]` should logically already be string | undefined even with old definition.

**Comment by Bobris** [comment]
Ouch https://github.com/microsoft/TypeScript/issues/13778
Ok this then actually fix of wrong TS type inference.

**Pull request merged**
