### PR TITLE
Automaton example added

### PR DESCRIPTION
**Pull request by wikancz**

### CODE REVIEW

**Comment by Bobris** [comment]
Whoa, big one, but it will need some small fixes. It should actually show you warnings is console - you just need to used unminified version of bobril.
instead of style: { float: "left", "margin-left": 10 } you need to write style: { cssFloat: "left", marginLeft: 10 }
BTW all these differences are described in documentation.

**Comment by wikancz** [comment]
Thank you for your comment. It should be fixed now.

**Comment by Bobris** [comment]
Perfect.

**Comment by Bobris** [comment]
Look at this modern ES2015 feature: https://github.com/Bobris/Bobril/commit/375772bca699f4a27e226aa1ad43c9df5e4180eb

**Pull request merged**
